name: GolderUnicorn
options:
  xcodeVersion: 15.1
  bundleIdPrefix: br.com.victorwads
  groupOrdering: 
    - order: [Service, Tests, Resources, Sources]
    - pattern: '^.*Screen$'
      order: [View, Presenter, Interactor, Entities, Assembly]
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 10.19.0
targets:
  GolderUnicorn:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 17.2
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseInstallations
    sources:
      - path: Sources
      - path: Resources
    scheme:
      language: pt-BR
      gatherCoverageData: true
      coverageTargets:
        - GolderUnicorn
      testTargets:
        - GolderUnicornTests
        - GolderUnicornUITests
    settings:
      base:
        CURRENT_PROJECT_VERSION: 8
        IPHONEOS_DEPLOYMENT_TARGET: 17.2
        MARKETING_VERSION: 1.0.0
#        OTHER_CODE_SIGN_FLAGS: --deep --timestamp
#      configs:
#        Debug:
#          CODE_SIGNING_REQUIRED: NO
#          CODE_SIGN_ENTITLEMENTS: Resources/Debug.entitlements
#          CODE_SIGN_IDENTITY: "-"
#          PROVISIONING_PROFILE_SPECIFIER: 
#        Release:
#          CODE_SIGN_ENTITLEMENTS: Resources/Release.entitlements
#          DEVELOPMENT_TEAM[sdk=macosx*]: DU6489YN3U
#          PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: UptimeLogger2027
#          CODE_SIGN_STYLE: Manual
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Uptime Logger
        CFBundleShortVersionString: "1.0.0"
        CFBundleURLTypes:
          - CFBundleURLName: "GolderUnicorn"
            CFBundleURLSchemes:
              - GolderUnicornFC
  GolderUnicornTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: GolderUnicorn
  GolderUnicornUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: GolderUnicorn
