name: GoldenUnicorn
options:
  xcodeVersion: 15.1
  bundleIdPrefix: br.com.victorwads
  groupOrdering: 
    - order: [Service, Tests, Resources, Sources]
    - pattern: '^.*Screen$'
      order: [View, Presenter, Interactor, Entities, Assembly]
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 10.19.0
targets:
  GoldenUnicorn:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 17.2
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseInstallations
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseRemoteConfigSwift
    sources:
      - path: Sources
      - path: Resources
    scheme:
      language: pt-BR
      gatherCoverageData: true
      coverageTargets:
        - GoldenUnicorn
      testTargets:
        - GoldenUnicornTests
        - GoldenUnicornUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.victorwads.goldenunicorn
        CURRENT_PROJECT_VERSION: 8
        IPHONEOS_DEPLOYMENT_TARGET: 17.2
        MARKETING_VERSION: 1.0.0
        CODE_SIGNING_REQUIRED: YES
        CODE_SIGN_ENTITLEMENTS: Resources/GoldenUnicorn.entitlements
        DEVELOPMENT_TEAM: DU6489YN3U
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Golden Unicorn
        CFBundleShortVersionString: "1.0.0"
        CFBundleURLTypes:
          - CFBundleURLName: "GoldenUnicorn"
            CFBundleURLSchemes:
              - GoldenUnicornFC
  GoldenUnicornTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: GoldenUnicorn
  GoldenUnicornUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: GoldenUnicorn
